<?php

namespace tuto\BackofficeBundle\Repository;

/**
 * DelegationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegationRepository extends \Doctrine\ORM\EntityRepository
{
}
