<?php

namespace tuto\BackofficeBundle\Repository;

/**
 * membershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipRepository extends \Doctrine\ORM\EntityRepository
{
}
