<?php

namespace tuto\BackofficeBundle\Repository;

/**
 * notificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function count($user)
	{
		$query = $this->createQueryBuilder('n');
		$query->SELECT ('COUNT(n)');
		$query->where('n.lu = false');
                 $query->andWhere($query->expr()->in('n.user', "SELECT u2.id FROM tuto\BackofficeBundle\Entity\User u2  WHERE u2.id = :user"));
		$query->setParameter('user', $user);
        return $query->getQuery()->getSingleScalarResult();
        
	}
}
