<?php

namespace tuto\BackofficeBundle\Repository;

/**
 * propositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByetat()
	{
		$query = $this->createQueryBuilder('p');
		$query->SELECT ('p') ;
		$query->where('p.etat = 4');
		
        return $query->getQuery()->getResult();
	}
        public function getNbprop($categorie_id)
	{
		$query = $this->createQueryBuilder('u');
		$query->SELECT ('COUNT(u)');
		$query->join('u.demande','d');
		$query->join('d.service','s');
		$query->where('s.Categorie = :id');
		$query->setParameter('id',$categorie_id);

        return $query->getQuery()->getSingleScalarResult();

	}
        public function count()
	{
		$query = $this->createQueryBuilder('n');
		$query->SELECT ('COUNT(n)');
		$query->where('n.etat = 4');
        return $query->getQuery()->getSingleScalarResult();
        
	}
}
