<?php

namespace tuto\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUtilisateurRepository extends EntityRepository
{
}
