<?php

namespace tuto\FrontofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Contact1Repository extends EntityRepository
{
}
